name: "Publish"
on:
  release:
    types: [published]

env:
  cache-version: 1

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.4

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4.0.2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        env:
          NODE_ENV: 'production'
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifact"
          path: |
            dist
            LICENSE
            README.md

  publish:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    needs:: build
    steps:
      - name: "Setup NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: "build-artifact"

      - name: "Publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm publish --provenance
